# docker-compose.yml
version: '3.8'

services:
  spoon:
    container_name: spoonfeed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - ./test-static:/usr/src/app/static