[package]
name = "spoonfeed-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
include_dir = "0.7.3"
mime_guess = "2.0.4"
tokio = { version = "1.29.0", features = ["full"] }
